"""Initial migration

Revision ID: 9321fe749309
Revises: ae346256b650
Create Date: 2025-06-04 14:00:31.058781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9321fe749309'
down_revision = 'ae346256b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_found_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('contact_info', sa.String(length=140), nullable=True),
    sa.Column('image_filename', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lost_found_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lost_found_item_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_found_item_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_user_id'))

    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('lost_found_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lost_found_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_lost_found_item_timestamp'))

    op.drop_table('lost_found_item')
    # ### end Alembic commands ###
